import pkg from '/home/claude/.npm-global/lib/node_modules/playwright/index.js';
const { chromium } = pkg;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const failed = [];
page.on('response', res => { if (res.status() >= 400) failed.push(`${res.status()} ${res.url()}`); });
const errs = [];
page.on('pageerror', err => errs.push(err.message));
const consoleErrs = [];
page.on('console', msg => { if (msg.type() === 'error') consoleErrs.push(msg.text().slice(0,300)); });
await page.goto('http://localhost:3316/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2500);
await page.screenshot({ path: '/tmp/user-final-hero.png' });
await page.evaluate(() => document.getElementById('contact')?.scrollIntoView());
await page.waitForTimeout(700);
await page.screenshot({ path: '/tmp/user-final-contact.png' });
console.log('FAILED REQUESTS:', failed.join('\n') || '(none)');
console.log('PAGE ERRORS:', errs.join('\n') || '(none)');
console.log('CONSOLE ERRORS:', consoleErrs.join('\n') || '(none)');
await browser.close();
